import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ImageUpload } from "../components/ImageUpload";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Learn <a href="https://nextjs.org">Signed Uploads</a>
        </h1>

        <div className={styles.grid}>
          <ImageUpload />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/kenny_io"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by @kenny_io
        </a>
      </footer>
    </div>
  );
}
